console.log("PRIMERA EDICION");
console.log("SEGUNDO Y ULTIMO COMMIT ")

//VER RESOLUCION Y PARA TEBR EB CUEBTA COMO SE HACE BIEN LOS DE LA TRANSFRECNIA DE GITHUB Y AL TERMINAL Y VS Y SEGUIR CON EL SIGUIENTE CAP.
